name: Build Docker Images
on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  build_docker_images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dsutil
        run: |
          pip3 install -U git+https://github.com/dclong/xinstall@master
          xinstall dsutil -ic
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Images
        run: |
          ./build_images.py
